# Generated by Django 3.2.6 on 2021-08-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='issue',
            field=models.CharField(default='fever', max_length=50),
            preserve_default=False,
        ),
    ]
